# Generated by Django 3.1.4 on 2020-12-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('node', models.CharField(max_length=200)),
                ('probe_enabled', models.BooleanField()),
                ('pager_enabled', models.BooleanField()),
                ('notice_level', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('group', 'node')},
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_switch', models.CharField(max_length=200)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enabler.probe')),
            ],
            options={
                'unique_together': {('probe', 'name')},
            },
        ),
    ]
